version: 0.2

phases:
  install:
    commands:
      # Use nvm that comes preinstalled in the CodeBuild standard images
      - export NVM_DIR="/root/.nvm"
      - . "$NVM_DIR/nvm.sh"
      - nvm install 20
      - nvm use 20
      - node -v
      - npm -v
      - corepack enable
      - corepack prepare yarn@1.22.22 --activate
  pre_build:
    commands:
      # Remove npm lockfile to avoid warnings about mixed package managers
      - rm -f package-lock.json || true
      - yarn install --frozen-lockfile || yarn install
  build:
    commands:
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
